### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by sakanamax**
update my Blog feed

### CODE REVIEW

**Comment by darix** [comment]
please remove the unrelated changes. TIA

**Comment by sakanamax** [comment]
Sorry darix, could you teach me which part is unreleated change? ^^

**Comment by darix** [comment]
I guess you want to modify: sakananote2english.blogspot.com but if you go to https://github.com/openSUSE/planet.opensuse.org/pull/24/files you see more changes than that.

1. it shows adding some .br blog
2. removing a comment

also github says the branch has conflicts which need to be resolved first so i cant even merge it right now. please pull again from https://github.com/openSUSE/planet.opensuse.org/ and rebase your change.

**Comment by sakanamax** [comment]
darix, yes, I want to modify: sakananote2english.blogspot.com
^^
I am not very good with github. could you teach me how to pull again from  https://github.com/openSUSE/planet.opensuse.org/ and rebase my change. 
Thanks ^^
sorry for take your time.

**Comment by lrupp** [comment]
Hi Max

I integrated your changes now separately, so I'm closing this request here. Hope that's ok for you.

Regards,
Lars

**Pull request closed without merging**
