### PR TITLE
Added crowbyte.org blog by Pierre Böckmann to feeds

### PR DESCRIPTION
**Pull request by crowbyte**

### CODE REVIEW

**Comment by cboltz** [comment]
Your RSS feed includes `<description>Sample Blog Description</description>`. You might want to fix that ;-)

I also have a question - currently your blog is only in german, but you also added your RSS feed to the english planet.opensuse.org. Will your future posts (also) be in english?

**Comment by crowbyte** [comment]
Two good hints.

1) I really should change that description. ;-) Thanks for the hint.

2) My blog already is available in german and english. But it sets the language from the browser if possible. So when you visit crowbyte.org you might end with english or german according to your browser settings (with english as default language and fallback for everything that is not matchable to en or de). :-) Hope that isn't true to the rss feed, too. But maybe it is better to deactivate that. Might confuse the users more than it might be of use.

**Comment by cboltz** [comment]
The automatic language switcher only makes sense if you allow people to override it - as long as `/de` and `/en` do what I'd expect, `/` can be an automatic redirect. That said, a manual "switch to $other_language" link is also a good solution ;-)

I just merged your blog into the planet.opensuse.org config. It will appear there in about an hour.

**Comment by crowbyte** [comment]
Thank you very much for the addition to planet.opensuse.org!

Auto language switcher is now turned off, because /en unfortunately does not what anyone would expect ;-) so crowbyte.org ist now english primary and if you want german you can go to crowbyte.org/de
The way you described does not work for me because it would unfortunately render many old links in social media and anywhere else useless which expect english articles on URLs like crowbyte.org/article-title :-)
I could configure a redirect route for any aticle on crowbyte.org/article-title to crowbyte.org/en/article-title, but I think the way it is now more fits my wish to have english as my primary and german only as an option for all my german fellows who simply prefer a simple read in their mother tongue. ;-)

**Pull request merged**
